import Navbar from "@/components/Navbar/navbar";
import "./global.css";

export const metadata = {
  title: "Next Course Web",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
